### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by limeng12** [yarden/MISO#117]
I installed MISO locally, and run many times, but seems one bam file seems have some problems when running MISO on it, others worked very well. The problem is:

Traceback (most recent call last):
  File "/N/u/liulab/Karst/limeng/myenv/bin/summarize_miso", line 9, in <module>
    load_entry_point('misopy==0.5.4', 'console_scripts', 'summarize_miso')()
  File "/gpfs/home/l/i/liulab/Karst/limeng/myenv/lib/python2.7/site-packages/misopy/summarize_miso.py", line 93, in main
    use_compressed=use_compressed)
  File "/gpfs/home/l/i/liulab/Karst/limeng/myenv/lib/python2.7/site-packages/misopy/samples_utils.py", line 285, in summarize_sampler_results
    samples_results = samples_obj.get_event_samples(event_name)
  File "/gpfs/home/l/i/liulab/Karst/limeng/myenv/lib/python2.7/site-packages/misopy/samples_utils.py", line 109, in get_event_samples
    samples = load_samples(f)
  File "/gpfs/home/l/i/liulab/Karst/limeng/myenv/lib/python2.7/site-packages/misopy/samples_utils.py", line 137, in load_samples
    data, h = csv2array(samples_in, skiprows=1, raw_header=True)
  File "/gpfs/home/l/i/liulab/Karst/limeng/myenv/lib/python2.7/site-packages/misopy/parse_csv.py", line 81, in csv2array
    cols = data_array[0,:]
IndexError: too many indices for array

**Comment by ibmuller** [comment]
I have the same problem. Did you solve it already?

**Comment by ajones-lab** [comment]
Hi,

Were either of you able to find a solution to this?

**Comment by ibmuller** [comment]
Yeah in my case it was that i had a very old version of samtools running.
Thanks.
________________________________

**Comment by ajones-lab** [comment]
Thank you! As in you sorted the bam file that you fed to miso with an old version of samtools? Its my understanding that the summarize_miso function isn't calling samtools?
