### ISSUE TITLE
About testing error

### ISSUE THREAD

**Issue by zhengjiantao** [yarden/MISO#130]
I have installed MISO. And all dependence is ok. But I got an error when MISO test. The code shown below:
python -m unittest discover misopy

The errors shown below(Maybe a little bit more information):
Testing gene-level Psi...
Executing: python /usr/local/lib/python2.7/dist-packages/misopy/index_gff.py --index /usr/local/lib/python2.7/dist-packages/misopy/gff-events/mm9/genes/Atp2b1.mm9.gff /usr/local/lib/python2.7/dist-packages/misopy/gff-events/mm9/indexed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/misopy/index_gff.py", line 199, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/misopy/index_gff.py", line 188, in main
    os.makedirs(output_dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/misopy/gff-events/mm9/indexed'
Executing: python /usr/local/lib/python2.7/dist-packages/misopy/run_events_analysis.py  --compute-genes-psi /usr/local/lib/python2.7/dist-packages/misopy/gff-events/mm9/indexed /usr/local/lib/python2.7/dist-packages/misopy/test-output/sam-output/c2c12.Atp2b1.sorted.bam --output-dir /usr/local/lib/python2.7/dist-packages/misopy/test-output/gene-psi-output --read-len 36  --paired-end 250 30 --use-cluster
MISO (Mixture of Isoforms model)
To run MISO, please use "miso" instead.
.Testing single-end SE event interface...
Executing: python /usr/local/lib/python2.7/dist-packages/misopy/run_events_analysis.py  --compute-events-psi se-sample /usr/local/lib/python2.7/dist-packages/misopy/test-data/se-counts/se_test.counts --output-dir /usr/local/lib/python2.7/dist-packages/misopy/test-output/SE-output --read-len 35 --overhang-len 4  --event-type SE --use-cluster 
MISO (Mixture of Isoforms model)
To run MISO, please use "miso" instead.
.Testing fr-unstranded...
Checking read  f_read  against  +
Checking read  f_read  against  -
Checking read  r_read  against  +
Checking read  r_read  against  -
Testing fr-firststrand...
.Testing conversion of SAM to BAM...
Executing: sam_to_bam --convert /usr/local/lib/python2.7/dist-packages/misopy/test-data/sam-data/c2c12.Atp2b1.sam /usr/local/lib/python2.7/dist-packages/misopy/test-output/sam-output
Converting SAM to BAM...
Traceback (most recent call last):
  File "/usr/local/bin/sam_to_bam", line 11, in <module>
    load_entry_point('misopy==0.5.4', 'console_scripts', 'sam_to_bam')()
  File "/usr/local/lib/python2.7/dist-packages/misopy/sam_to_bam.py", line 63, in main
    sam_to_bam(sam_filename, output_dir, header_ref=ref)
  File "/usr/local/lib/python2.7/dist-packages/misopy/sam_to_bam.py", line 13, in sam_to_bam
    os.makedirs(output_dir)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/misopy/test-output'
FTesting gene-level Psi...
Testing GFF indexing of: /usr/local/lib/python2.7/dist-packages/misopy/gff-events/mm9/genes/Atp2b1.mm9.gff
Executing: index_gff --index /usr/local/lib/python2.7/dist-packages/misopy/gff-events/mm9/genes/Atp2b1.mm9.gff /usr/local/lib/python2.7/dist-packages/misopy/gff-events/mm9/genes/Atp2b1/indexed
Traceback (most recent call last):
  File "/usr/local/bin/index_gff", line 11, in <module>
    load_entry_point('misopy==0.5.4', 'console_scripts', 'index_gff')()
  File "/usr/local/lib/python2.7/dist-packages/misopy/index_gff.py", line 188, in main
    os.makedirs(output_dir)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/misopy/gff-events/mm9/genes/Atp2b1'
Executing: miso --run /usr/local/lib/python2.7/dist-packages/misopy/gff-events/mm9/genes/Atp2b1/indexed /usr/local/lib/python2.7/dist-packages/misopy/test-output/sam-output/c2c12.Atp2b1.sorted.bam --output-dir /usr/local/lib/python2.7/dist-packages/misopy/test-output/gene-psi-output --read-len 36 
MISO (Mixture of Isoforms model)
Probabilistic analysis of RNA-Seq data for detecting differential isoforms
Use --help argument to view options.

Using MISO settings file: /usr/local/lib/python2.7/dist-packages/misopy/settings/miso_settings.txt
Traceback (most recent call last):
  File "/usr/local/bin/miso", line 11, in <module>
    load_entry_point('misopy==0.5.4', 'console_scripts', 'miso')()
  File "/usr/local/lib/python2.7/dist-packages/misopy/miso.py", line 563, in main
    main_logger = get_main_logger(logs_output_dir)
  File "/usr/local/lib/python2.7/dist-packages/misopy/miso.py", line 54, in get_main_logger
    fh = logging.FileHandler(logger_fname)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/misopy/test-output/gene-psi-output/logs/main.2019-01-02_15-43-58.log'
.
======================================================================
FAIL: test_a_sam_to_bam (misopy.test_miso.TestMISO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/misopy/test_miso.py", line 51, in test_a_sam_to_bam
    "c2c12.Atp2b1.sorted.bam")))
AssertionError

----------------------------------------------------------------------
Ran 5 tests in 2.677s
FAILED (failures=1)

I saw someone says that error has to do with the version of samtools. Like -o refers to output path.
So should I solve the test error? or say it will not affect normal use?

Thanks.

**Comment by rolanddb** [comment]
I'm facing the same issue.
