### ISSUE TITLE
import pysplicing

### ISSUE THREAD

**Issue by MurliNair** [yarden/MISO#136]
Hi, 
I just installed misopy using pip. I was testing it by trying to import misopy and pysplicing, import misopy works fine, but pysplicing is giving the following error.   
>>> import misopy
>>> import pysplicing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/pysplicing/__init__.py", line 2
    MISO_START_AUTO=0L
                     ^
SyntaxError: invalid syntax
>>>

Thanks for your help. 
Cheers../Murli

**Comment by MurliNair** [comment]
I tried reinstalling it and it still gives me an error. 
Tue May 28, 10:54:05 [root@genomics ~]# pip --version
pip 19.1.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

Tue May 28, 10:56:26 [root@genomics ~]# pip install misopy
Collecting misopy
  Using cached https://files.pythonhosted.org/packages/1e/1c/1ee24b5ed82b1c3b673345ecfc5e7a505273cfe5b450d6fc05479f1ad641/misopy-0.5.4.tar.gz
Requirement already satisfied: matplotlib in /usr/local/lib64/python3.6/site-packages (from misopy) (3.1.0)
Requirement already satisfied: numpy>=1.5.0 in /usr/local/lib64/python3.6/site-packages (from misopy) (1.16.3)
Requirement already satisfied: scipy>=0.9.0 in /usr/local/lib64/python3.6/site-packages (from misopy) (1.3.0)
Requirement already satisfied: pysam>=0.6.0 in /usr/local/lib64/python3.6/site-packages (from misopy) (0.15.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib64/python3.6/site-packages (from matplotlib->misopy) (1.1.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/site-packages (from matplotlib->misopy) (2.8.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/site-packages (from matplotlib->misopy) (2.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/site-packages (from matplotlib->misopy) (0.10.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib->misopy) (40.6.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/site-packages (from python-dateutil>=2.1->matplotlib->misopy) (1.12.0)
Installing collected packages: misopy
  Running setup.py install for misopy ... done
Successfully installed misopy-0.5.4

Tue May 28, 11:02:17 [root@genomics ~]# python3
Python 3.6.8 (default, Apr 25 2019, 21:02:35)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import misopy
>>> import pysplicing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/pysplicing/__init__.py", line 2
    MISO_START_AUTO=0L
                     ^
SyntaxError: invalid syntax
>>>
=======================
Tue May 28, 11:54:45 [root@genomics ~/Downloads/test]# python3 -m  unittest discover  misopy -v
misopy.test_cluster (unittest.loader._FailedTest) ... ERROR
misopy.test_miso (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: misopy.test_cluster (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: misopy.test_cluster
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/usr/local/lib64/python3.6/site-packages/misopy/test_cluster.py", line 30
    print "Testing single-end SE event interface..."
                                                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Testing single-end SE event interface...")?


======================================================================
ERROR: misopy.test_miso (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: misopy.test_miso
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/usr/local/lib64/python3.6/site-packages/misopy/test_miso.py", line 39
    print "Testing conversion of SAM to BAM..."
                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Testing conversion of SAM to BAM...")?


----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)

**Comment by hua-2019-git** [comment]
Hi, i am also meet the same question, pysplicing is giving the following error.
import pysplicing
Traceback (most recent call last):
File "", line 1, in
File "/usr/local/lib64/python3.6/site-packages/pysplicing/init.py", line 2
MISO_START_AUTO=0L
^
SyntaxError: invalid syntax

I'd like to know how you solved this problem. Thank you very much

**Comment by obenno** [comment]
Hi,
I think the package was written by python2, maybe you should try python2.7.

**Comment by ttran2020** [comment]
> Hi,
> I just installed misopy using pip. I was testing it by trying to import misopy and pysplicing, import misopy works fine, but pysplicing is giving the following error.
> 
> > > > import misopy
> > > > import pysplicing
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/usr/local/lib64/python3.6/site-packages/pysplicing/**init**.py", line 2
> > > > MISO_START_AUTO=0L
> > > > ^
> > > > SyntaxError: invalid syntax
> 
> Thanks for your help.
> Cheers../Murli

Murli - Did you have a chance to address the issues? If yes, I would appreciate it if you can share. I got the same issue. Thanks.
T

**Comment by mbradyneeley** [comment]
I encountered the same issue and like obenno commented using python2 instead of python3, import pysplicing was succesful.
