### ISSUE TITLE
Installing and running miso 

### ISSUE THREAD

**Issue by Oliverfeudj** [yarden/MISO#147]
Hello
I am trying to run miso but I am getting this error after having installed it successfully 

`debian@username:~$ miso`
Traceback (most recent call last):
  File "/home/debian/.local/bin/miso", line 5, in <module>
    from misopy.miso import main
  File "/home/debian/.local/lib/python3.7/site-packages/misopy/miso.py", line 62
    print "MISO (Mixture of Isoforms model)"
                                           ^
SyntaxError: invalid syntax

**Comment by margaretwoodhouse** [comment]
I'm having the same issue. I used 

`pip install --user misopy`

Edit: I realized that the instructions say for python 2.6 and above, but that does NOT include python3.

**Comment by Oliverfeudj** [comment]
You can install it through a conda environment that you can create with python 2.6 or 2.7
Miso apparently doesn't support python 3.
--
Sent from Mail.ru app for Android Tuesday, 04 April 2023, 07:03PM +02:00 from margaretwoodhouse  ***@***.*** :
