### ISSUE TITLE
strand_rule error

### ISSUE THREAD

**Issue by dauss75** [yarden/MISO#82]
Hello,

I am getting strand_rule related error. When I check the code, the strand_rule variable was set to fr-unstranded which seems fine to me.  Do you have any thoughts on this issue?  Many thanks!  

Using MISO settings file: /opt/galaxy/tools/miso/settings/miso_settings.txt
Computing Psi for genes from file...
- Input file: /scratch/galaxy/files/006/dataset_6084_files/batch-genes/batch-0_genes.txt
  Computing Psi for 1 genes...
- ENSG00000001617
- GFF filename: /scratch/galaxy/files/006/dataset_6076_files/chr3/ENSG00000001617.pickle
- BAM: /scratch/galaxy/files/006/dataset_6084_files/input_bam.bam
- Outputting to: /scratch/galaxy/files/006/dataset_6084_files
  Loading BAM filename from: /scratch/galaxy/files/006/dataset_6084_files/input_bam.bam
  Loading took 0.03 seconds
  Traceback (most recent call last):
  File "/opt/galaxy/tools/miso/run_miso.py", line 490, in <module>
    main()
  File "/opt/galaxy/tools/miso/run_miso.py", line 434, in main
    run_compute_genes_from_file(options)
  File "/opt/galaxy/tools/miso/run_miso.py", line 254, in run_compute_genes_from_file
    event_type=options.event_type)
  File "/opt/galaxy/tools/miso/run_miso.py", line 139, in compute_gene_psi
    given_read_len=read_len)
  TypeError: sam_parse_reads() got an unexpected keyword argument 'strand_rule'

**Comment by dauss75** [comment]
somehow old version of sam_util.py was present that didn't understand strand_rule..
