### ISSUE TITLE
IndexError when summarizing and comparing MISO results

### ISSUE THREAD

**Issue by althornt** [yarden/MISO#98]
I was able to run MISO without errors but I get the following error when trying to summarize or compare the results.

when trying to run the following command:
summarize_miso --summarize-samples 15_cfz_AMO1_4_S6 summary_15_cfz_AMO1_4_S6

I get the error:
Traceback (most recent call last):
  File "/pod/home/althornt/miso/miso/bin/compare_miso", line 9, in <module>
    load_entry_point('misopy==0.5.3', 'console_scripts', 'compare_miso')()
  File "/pod/home/althornt/miso/miso/lib/python2.7/site-packages/misopy/compare_miso.py", line 94, in main
    use_compressed=use_compressed)
  File "/pod/home/althornt/miso/miso/lib/python2.7/site-packages/misopy/hypothesis_test.py", line 289, in output_samples_comparison
    confidence_level=alpha)
  File "/pod/home/althornt/miso/miso/lib/python2.7/site-packages/misopy/credible_intervals.py", line 22, in format_credible_intervals
    cred_interval = compute_credible_intervals(samples)
  File "/pod/home/althornt/miso/miso/lib/python2.7/site-packages/misopy/credible_intervals.py", line 54, in compute_credible_intervals
    cred_interval = [samples[lower_bound_indx], samples[upper_bound_indx]]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Any help would be greatly appreciated!

**Comment by KatyBrown** [comment]
Hi - I also have this problem when running summarize_miso and compare_miso.  Thanks!

**Comment by maofengbiao** [comment]
Hi, I also have this problem. But how to solve it?

**Comment by maofengbiao** [comment]
Who know the email address of the author?

**Comment by KatyBrown** [comment]
I have "fixed" it in my local copy by altering credible_intervals.py - changing 

```
lower_bound_indx = round((alpha/2)*num_samples) - 1
upper_bound_indx = round((1-alpha/2)*num_samples) - 1
```

to

```
lower_bound_indx = int(round((alpha/2)*num_samples) - 1)
upper_bound_indx = int(round((1-alpha/2)*num_samples) - 1)
```

The code now runs, however I can't totally understand what this section does so I don't know if this workaround will have unwanted effects.

**Comment by althornt** [comment]
Thanks for the fix, Katy!

**Comment by maofengbiao** [comment]
Thanks a lot.

2017-04-17 0:05 GMT-04:00 Alexis <notifications@github.com>:

**Comment by brightchan** [comment]
Having the same problem and solved with Katy's method, although don't know if it's right to do so. Thanks!

**Comment by biobenkj** [comment]
Also referenced in #103 as a fix and per @roryk it is now incorporated as a fix.
